# Site settings
title: UCSB CS Graduate Representatives
email: gradreps@cs.ucsb.edu
description: > # this means to ignore newlines until next entry 
    University of California, Santa Barbara
    Computer Science
    Graduate Student Representatives

footer_1: University of California, Santa Barbara
footer_2: Computer Science Graduate Student Representatives
baseurl: "/~greps" # the subpath of your site, e.g. /blog/
#url: "https://ucsb-cs-graduate-representatives.github.io" # the base hostname & protocol for your site
url: "http://cs.ucsb.edu/"
github_username: UCSB-CS-Graduate-Representatives
permalink: pretty
destination: ~/public_html/

# Build settings
markdown: kramdown

# Navigation toolbar:
navigation:
    - text: What we do
      url: /what-we-do/
    - text: Who we are
      url: /who-we-are/
    - text: Contact us
      url: /contact/

collections:
    GradReps: # Collection of GradRep profiles (in /_GradReps/)
        output: true # Each GradRep gets a html webpage
        permalink: /gradrep/:path/
